AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-pebble

  Sample SAM Template for aws-sam-pebble

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 30
    Handler: index.handler
  Api:
    EndpointConfiguration: REGIONAL
    Cors: "'*'"

Resources:
  SendEmailContactUsFunction:
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: send-email-contact-us/
      Environment:
        Variables:
          CORS_ORIGIN: "'*'"
      Events:
        SendEmailContactUs:
          # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Type: Api
          Properties:
            Path: /send-email-contact-us
            Method: post
      Policies:
        - SESCrudPolicy:
            IdentityName: "*"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SendEmailContactUsApi:
    Description: "API Gateway endpoint URL for Prod stage for SendEmailContactUs function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send-email-contact-us"
